name: MooColorPicker
author: lorenzo.stanco
category: Interface
tags: [color, interface, forms]
demo: http://jsfiddle.net/MSPb7/5/
docs: http://github.com/lorenzos/MooColorPicker/blob/master/README.md