name: MooColorPicker
author: lorenzo.stanco
category: Interface
tags: [color, interface, forms]
demo: http://jsfiddle.net/MSPb7/115/
docs: http://wiki.github.com/lorenzos/MooColorPicker/docs
current: 1.3
